apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: multitool
        env:
        - name: HTTP_PORT
          value: "8080"
