apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-hello-world-app
  name: hello-world
  namespace: default
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
        name: hello-w-port
