apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-netology-web-app
  name: netology-web
  namespace: default
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
        name: netology-w-port

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: my-netology-web-app
  ports:
    - name: netology-s-port
      protocol: TCP
      port: 8001
      targetPort: netology-w-port
