{
 "title": "Netology dashboard",
 "time": { "from": "2023-03-24T10:43:11.021Z", "to": "2023-03-24T12:29:02.397Z" },
 "panels": [
  {
   "title": "Disk free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Disk free"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "Load average 1 min"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "Load average 5 min"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "Load average 15 min"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$__rate_interval])) * 100"
    }
   ]
  }
 ]
}