apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep-vol
  name: dep-vol
  namespace: default
spec:
  selector:
    matchLabels:
      app: dep-vol
  replicas: 1
  template:
    metadata:
      labels:
        app: dep-vol
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        name: multitool
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: pvc-nfs
