apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task2
  name: task2
  namespace: default
spec:
  selector:
    matchLabels:
      app: task2
  replicas: 1
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - image: nginx:1.24.0
        imagePullPolicy: IfNotPresent
        name: nginx
      initContainers:
      - image: busybox
        name: init-svc
        command: ['sh', '-c', 'until getent hosts netology-svc; do echo waiting for netology-svc; sleep 2; done;']
