apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: netology-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: netology-nginx
  template:
    metadata:
      labels:
        app: netology-nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
