apiVersion: v1
kind: Deployment
metadata:
  name: deployment-task1
  labels:
    app: task1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: multitool
        image: multitool
        ports:
        - containerPort: 8001
