apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivan
  namespace: my-dev
subjects:
- kind: User
  name: ivan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
