apiVersion: v1
kind: Pod
metadata:
  labels:
    app: task2
  name: task2
  namespace: default
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8090
        name: netology-w-port

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: task2
  ports:
    - name: for-nginx
      port: 8001
      targetPort: 80
    - name: for-multitool
      port: 8002
      targetPort: 8080
