apiVersion: v1
kind: Service
metadata:
  name: netology-svc1
spec:
  selector:
    app: deploy1
  ports:
    - name: for-nginx
      port: 9001
      targetPort: 80
    - name: for-multitool
      port: 9002
      targetPort: 8080
