apiVersion: v1
kind: Namespace
metadata:
  name: netology-api-task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  namespace: netology-api-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-app
  template:
    metadata:
      namespace: netology-api-task
      labels:
        app: netology-app
    spec:
      containers:
        - name: netology-api-task
          image: cr.yandex/crph10lcdoj8cuq7480c/centos:7
          imagePullPolicy: Always
