apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: task1
  ports:
    - name: for-nginx
      port: 8001
      targetPort: 80
    - name: for-multitool
      port: 8002
      targetPort: 8080
